### ISSUE TITLE
My presence is "unknown"

### ISSUE THREAD

**Issue by senky** [pusher/chatkit-client-js#109]
Hi,
after updating the client to 1.0.2 I experience this strange behaviour that `room.users.presence.state` is `unknown` for me. It is online or offline for other users, but currently logged in user is unknown.

**Comment by mdpye** [comment]
Hi @senky.

- Are you checking the state immediately after connection?
- Does it get updated via `onPresenceChange` at any point, or is it stuck on `unknown` for the whole session.
- In fact, does it get updated via `onPresenceChange`, but you do not see that change reflected in `room.users.presence.state` after the hook fires?

Thanks

**Comment by williamluke4** [comment]
Hi @mdpye,
I have the same issue has @senky. 
*  Are you checking the state immediately after connection?
    * No, I'm checking the state on a message object recived after a room connection
* Does it get updated via onPresenceChange at any point, or is it stuck on unknown for the whole session.
    * onPresenceChange will update the state to the correct value

**Comment by williamluke4** [comment]
Also,
* Why is there `unknown` surely the user is `offline` or `online`? 
* Currently checking the presence on a message that the currentUser sent will always show `unknown`

**Comment by mdpye** [comment]
Thanks for the info @williamluke4. There is indeed a bug where the current user's online state is not subscribed to. PR #107 should resolve it in the next patch version.

The `unknown` state exists in case the presence service is unavailable (which we'd prefer not to block all progress in the SDK), or to return before the initial state is available.

We no longer block the resolution of the initial connection call on all presence states being fetched (again, because we want the SDK to be ready to use ASAP and to reduce dependencies which would lead critial operations like subscribing to a room to fail on the client). In order to allow UI transitions to be smooth or more muted, we include the previous state and you can test if the previous state is `unknown` to recognise an initial state and dial down any big "Your friend is now online!" toasts in the UI :)

**Comment by mdpye** [comment]
Fix released some time ago and verified by other users with the same issue. Please re-open if this issue is still affecting you as of 1.0.2.
