### ISSUE TITLE
Reactivity on room presence is lost

### ISSUE THREAD

**Issue by senky** [pusher/chatkit-client-js#112]
Hello,
I didn't investigate it deeper, just an observation.

I use VUE to wrap around Chatkit. One of great features of older versions (<1.0.0) was automatic reactivity of `room.users`. This is lost now. I didn't change anything on my side so I assume it's something on your side. Could you confirm, please? I was very happy I didn't have to subscribe to `onPresenceChanged` to track presence and then filter by room members. `room.users` just worked magically.

**Comment by callum-oakley** [comment]
Hi! `room.users` certainly _should_ still be updating automatically. How exactly are you using it so I can see if I can reproduce?

**Comment by senky** [comment]
So I have a computed property:
```javascript
computed: {
		users() {
			if (typeof this.currentUser.rooms !== 'object') {
				return [];
			}

			const room = this.currentUser.rooms.find(room => room.id == this.roomId);
			if (room) {
				return room.users;
			}
			return [];
		}
	}
```

And then I iterate through the users like this in my template:
```vue
<Person v-for="user in users" ...
```

This was enough for VUE to track changes in `room.users`. But now that feature is lost.

**Comment by callum-oakley** [comment]
The only thing that I can think of that's changed in the move to 1.0 is that you now need to be subscribed to a room to receive updates about it's users. But if you weren't subscribed you should be seeing an error... Are you subscribed to the room that you're checking above?

**Comment by senky** [comment]
@callum-oakley I investigated a little and this is what I found.

`presence` key in `room.users[<userId>]` is the only key that is not watched by VUE's reactive getter/setters. Why is that? Is that key added later in the code than the others?

**Comment by callum-oakley** [comment]
Interesting. The way presence works under the hood has indeed changed quite a lot for 1.0. The logic from src/presence-subscription.js has mostly moved to [src/user-presence-subscription.js](https://github.com/pusher/chatkit-client-js/blob/master/src/user-presence-subscription.js), so it's not a fundamental change. The reason VUE doesn't pick up the presence changes is probably because [`presence` is a getter](https://github.com/pusher/chatkit-client-js/blob/master/src/user.js#L12-L16)?

[This issue](https://github.com/vuejs/vuex/issues/754) seems to imply that you might be able to work around this by adding presence to your computed properties? Though I'm not sure why this would have changed for 1.0, because [presence was a getter in 0.7 too](https://github.com/pusher/chatkit-client-js/blob/0.7.18/src/user.js#L12-L18) 🤔

**Comment by hamchapman** [comment]
@senky were you able to get this working?

**Comment by senky** [comment]
What I did is I have a `presenceCounter` data which gets incremented in `onPresenceChange` and this counter forces the list of users to be updated. It works this way.
