### ISSUE TITLE
PushNotification for chatkit

### ISSUE THREAD

**Issue by tribeAppMobile** [pusher/chatkit-client-js#123]
Using the chatkit and want to enable push notification. But it shows error message 

undefined is not a function (evaluating '_currentUser.enablePushNotifications()'

In pusher docs, we just need to call enablePushNotifications after connect successful through ChatManager

Any solutions ?

**Comment by gianpaj** [comment]
I believe you're confusing JS code with Swift :)

https://docs.pusher.com/chatkit/push_notifications/setup-ios#enable-push-notifications

In order to enable push notifications (properly) on a React Native app, there needs to be some native code (Java/Swift) + some JavaScript method that will be invoked when for example the notification is pressed [onNotificationOpened() RN Firebase](https://rnfirebase.io/docs/v5.x.x/notifications/receiving-notifications#App-in-Foreground-and-background)

I believe the nice folks at Pusher are working hard to make this happen 😊

**Comment by hamchapman** [comment]
Yep, right now push notifications aren't supported in the JS SDK. I'll close this issue for now but rest assured that we're aware of the requests for push notification support in the JS SDK 👍

**Comment by rafaismyname** [comment]
@hamchapman any news on this?

push notification is a *MUST* in our RN App requirements and this could lead us to choose other solution over chatkit :(

also, why closing the issue if this is, imo, a pending feature request?

best!

**Comment by vivangkumar** [comment]
@rafaismyname We'll be working on supporting that very soon in RN. However, for now we offer web hooks that you can use to trigger push notifications on your end. This is not ideal and just a workaround, but like I mentioned, it is something we will be working on to support.

**Comment by rafaismyname** [comment]
@vivangkumar ok cool!
just one question... chatkit's console shows some kind of limit for webhooks, but chatkit's pricing page doesn't mention anything about webhook limits. Is there any limiting for webhooks?
if there is not, using webhooks for push notifications should be fine :)

**Comment by agaase** [comment]
We need this feature badly too! Any kind of workaround are very hacky (at least what we implemented) . We might have to look for alternatives (as we grow) if this is not implemented soon!

**Comment by orlyapps** [comment]
any update or timeline for this feature?

**Comment by TreeMan360** [comment]
@vivangkumar I want to use Chatkit in an Expo project (iOS, Android, & Web) - is the recommended approach to use web hooks for this at the moment?

Do you have plans to support Expo out-of-the-box?

Are there any limitations of the web hook approach I should be aware of?

Thanks!
