### ISSUE TITLE
errors not handled when using async/await

### ISSUE THREAD

**Issue by anchetaWern** [pusher/chatkit-client-js#130]
I'm using Chatkit with the async/await pattern. The problem is with error handling. It seems to be ignoring the `try..catch`. Basically, what I'm trying to do is to make the user leave the chat room before I search for the joinable rooms. Because if I don't call the `leaveRoom` method, the room won't actually show up when searching for joinable rooms (because Chatkit still sees that the user is in the room). If after that the room still doesn't exist, I attempt to create it (if it already exists, I just subscribe to it).

```
initializeChatRoom = async (room) => {
  try {
    await this.currentUser.leaveRoom({ roomId: room.id });
    await this.currentUser.roomSubscriptions[room.id].cancel();
  } catch (e) {
    console.log("error leaving room: ", e);
  }

  let chat_room = null;
  try {
    let rooms = await this.currentUser.getJoinableRooms();
    chat_room = rooms.find(room => {
      return room.name == this.roomName;
    });
  } catch (e) {
    console.log("error getting joinable rooms: ", e);
  }

  if (!chat_room) {
    try {
      let room = await this.currentUser.createRoom({
        name: this.roomName,
        private: false
      });

      await this.subscribeToRoom(room.id);
     
    } catch (e) {
      console.log("error creating room: ", e);
    }
  } else {
    await this.subscribeToRoom(chat_room.id);
  }

}
```

The error happens on the first `try..catch` block when the user hasn't joined the room yet:

<img width="437" alt="screen shot 2019-01-03 at 6 33 23 pm" src="https://user-images.githubusercontent.com/743603/50633817-a719d380-0f87-11e9-90db-15d6a5dfadde.png">

Any ideas why it's returning an error even though I wrapped it in a `try..catch` block?

**Comment by callum-oakley** [comment]
Sorry for the delayed response. It looks like you're seeing this because the default logger reports the authorization error with `console.error`, and react native will crash your app with the red box for any use of `console.error` 🤦‍♂️ (only while in development mode I believe)

We might want to remove all use of `console.error` in the SDK for that reason, so thanks for bringing this to our attention. You should be able to fix your immediate problem by [providing a custom logger](https://docs.pusher.com/chatkit/reference/javascript#logger) to the `ChatManager` constructor. Something like

```js
const chatManager = new ChatManager({
  userId: USER_ID,
  instanceLocator: INSTANCE_LOCATOR,
  tokenProvider: new TokenProvider({ url: TOKEN_PROVIDER_URL }),
  logger: {
    error: console.log, // normally this would be console.error
    warn: console.log,
    info: () => {},
    debug: () => {},
    verbose: () => {},
  },
})
```

Alternatively, you could [disable the "crash the app on `console.error`" behaviour of react-native by setting](https://github.com/facebook/react-native/blob/master/Libraries/Core/ExceptionsManager.js#L104-L107)

```js
console.reportErrorsAsExceptions = false
```

**Comment by callum-oakley** [comment]
Closing this as stale.
