### ISSUE TITLE
"Received message for unknown subscription ID" error 

### ISSUE THREAD

**Issue by garvitkhandelwal** [pusher/chatkit-client-js#156]
My app was working absolutely fine until today my messages are not getting displayed. Whenever I click on a room, this error is logged out.

![](https://user-images.githubusercontent.com/24408454/55426030-6db22d80-55a1-11e9-840a-b32577d73645.png)

The messages are getting stored in Chatkit but are not able to be retrieved.
Can someone tell me why this is happening?

**Comment by callum-oakley** [comment]
This looks like what would happen if you were receiving messages in rooms which you have just unsubscribed from. Are there any other errors in the logs which look suspicious? If not would it be possible to either see either (or both!):

- a small reproduction of the problem which I can run in order to try and figure out what's going on
- a copy of the websocket frames (you can find these in the chrome developer tools) for when the problem is happening

**Comment by garvitkhandelwal** [comment]
![Screenshot (70)](https://user-images.githubusercontent.com/24408454/55514184-11c0d500-5685-11e9-98b3-0cdf93509b3a.png)
This is the websocket whenever I click on a room ("Test" in my case).
Also I'm relatively new to this so please don't mind me not getting things done correctly.

**Comment by callum-oakley** [comment]
If you re-load that page *after* opening the network tab you should see the websocket listed. [Then if you click on that and you'll be able to see the frames.](https://developers.google.com/web/tools/chrome-devtools/network/reference#frames) Otherwise, happy for you to send us some code and we'll see if we can figure out what's going on over here. (if you'd rather not post it here you can shoot an email to support@pusher.com)

**Comment by garvitkhandelwal** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/24408454/55621499-4fc01500-57bb-11e9-82da-ab87499cf21a.png)
These are the websocket frames. 
Also to view the source code, can you please go on to https://github.com/garvitkhandelwal/chatapp . This has the complete updated code. The problem started when I upgraded chatkit to a newer version.
 Thank you for helping.

**Comment by garvitkhandelwal** [comment]
@callum-oakley  Anything I can do to fix this?

**Comment by callum-oakley** [comment]
Sorry for the delay @garvitkhandelwal. The screenshot doesn't contain the websocket frames Can you filter the traffic by `ws` in the bar at the top, and then click on the websocket to see the frames? Should look something like this:

![Screenshot 2019-04-12 at 10 32 57](https://user-images.githubusercontent.com/11499545/56027688-6c55d300-5d0e-11e9-9681-780dc6a5813e.png)

Alternatively (and more helpfully in the long run!) if you could provide us with a minimal project that reproduces the issue then we can debug it at our end.

**Comment by callum-oakley** [comment]
Closing as stale.
