### ISSUE TITLE
currentUser.removeUserFromRoom doesn't update currentUser.users

### ISSUE THREAD

**Issue by anchetaWern** [pusher/chatkit-client-js#158]
I was expecting that `currentUser.removeUserFromRoom` will automatically update the users in the room contained in `currentUser.users` because `currentUser.addUserToRoom` automatically adds the new user to `currentUser.users`

Or is there a better way of getting the list of current users in the room (and their presence) without having to use the [server APIs](https://docs.pusher.com/chatkit/reference/server-node#get-a-room)?

**Comment by callum-oakley** [comment]
`currentUser.removeUserFromRoom` should result in the `onUserLeftRoom` hook being fired, and the user being removed from `room.users`. `currentUser.users` is a bit of a weird beast, because it contains every user that the client has ever seen, you're much better off always using the `users` property on the `room` object.

**Comment by anchetaWern** [comment]
ok. thanks! will try this.

**Comment by callum-oakley** [comment]
10 months late but... You can access `room.users` anywhere you have a room object. So in any of the hooks where you receive a room or at any time in `currentUser.rooms`. Please re-open if this is still an issue. (Or [contact support](mailto:support@pusher.com) for a much faster response!)
