### ISSUE TITLE
subscribe to room fails if cursors:read:get permission isn't set

### ISSUE THREAD

**Issue by anchetaWern** [pusher/chatkit-client-js#164]
Not sure why, but if I remove the `cursors:read:get` permission, I get an error that says there's a missing permission and it points me to this page: https://pusher.com/docs/errors/services/chatkit_authorizer/authorization/missing_permission

My question is why this permission is needed if I'm not using the cursor functionality in my app?

**Comment by callum-oakley** [comment]
The client will always try and get cursors, since it doesn't know if you're using them or not! We would like to give you more fine grained control over whether the client should get cursors or not (and other related things, presence etc.) but at the moment it's pretty much a requirement to have `cursors:read:get` to use this SDK.

**Comment by callum-oakley** [comment]
Closing as stale. None of our SDKs really support non-standard sets of permissions as it stands. If you have a use case for this please [contact support](mailto:support@pusher.com) so that we can prioritise the work.
