### ISSUE TITLE
How to list all the available Users ?

### ISSUE THREAD

**Issue by amitpatil321** [pusher/chatkit-client-js#172]
I am trying to build slack clone where i want to list all the users in the sidebar. But with the existing js client, I don't see any way to list all the users.

I thought about looping through all the rooms and collect users of all the rooms but even that doesn't cover all the users Because there are few users who are not subscribed to any room.

**Comment by amitpatil321** [comment]
In the meantime, I used a workaround to solve this problem. A simple solution I used is, by default I am subscribing a new user to "general" room. And then i get list of all the available users from general room object.

[https://github.com/amitpatil321/React-Slack/blob/a6ee9bd1db37e9aee5ebf3f0fa514540d46cfca7/server/index.js#L29](url)

**Comment by callum-oakley** [comment]
Thanks for the request. This is on our internal backlog but I'm closing the issue because it's more of a feature request for the product as a whole than for this SDK specifically. If this is important for your use case please [contact support](support@pusher.com) with further details so we can prioritise the work.
