### ISSUE TITLE
Pusher - despicable behavior! Must read!

### ISSUE THREAD

**Issue by SiteSplat** [pusher/chatkit-client-js#182]
I just received a new email about prices.  You cannot be serious. 

After spending thousands of dollars and over a year in building a custom chat with pusher API (after deciding to leave PuBNub for pusher.)  I cannot believe where this is headed. months and months of crazy work with many setbacks as the pusher developer team was having a super hard time getting things straight with the pusher API., log issues, problems in keeping a reliable connection, errors after errors and just being used pretty much as "Guinea pig".

Never mind failure as well from the pusher marketing team advertising futures that were not even existent. 
like this one for example: https://github.com/pusher/chatkit-client-js/issues/169

had to make many adjustments and hacks to provide to my clients the features that pusher advertised to begin with and never worked. (were never there?)
so now you guys are backtracking again? every few months you guys keep changing up packages? 

absolutely outrageous and the most despicable aspect is the fact they you backtracked your own words 4 times since June 2018! 

changes since last year:

**-June 2018:**
https://gyazo.com/34a578a029b6fae5fbacc449919a8a7b
[img]https://gyazo.com/34a578a029b6fae5fbacc449919a8a7b.png[/img]
will have a free tier that is up to 1500 monthly peak concurrent users (up to 5 connections per user), 30 days of message retention, and we are still working out how many rich media downloads will be included. 

**- at some point in 2018 [/b](I think around October they quietly came up with:)**
https://gyazo.com/7f3d025516aefbe0010363431739d9d0
[img]https://gyazo.com/7f3d025516aefbe0010363431739d9d0.png[/img]

**-March 2019 (they scrapped that and increasing everything for the free plan)**
https://gyazo.com/b4a81db7dba83394e9fffcdc11e15674
we are making all our new plans more generous, and increasing the limits on unique users and messages per month.
[img]https://gyazo.com/b4a81db7dba83394e9fffcdc11e15674.png[/img]

**-June 25, 2019[/b] (finally scrapped everything all together )**
[img]https://gyazo.com/a09f1084c3f66256761ec7953a4e572d.png[/img]
https://gyazo.com/a09f1084c3f66256761ec7953a4e572d

This practice is absolutely dishonest and respectfully we demand that you respect your words and regarding the free usage since March 2019 and bring back that tier:
https://gyazo.com/c5adafa012a7baf07374b8226ed51cef

This is really quite disappointing after so much work and money went into this project.
not only I speak from a developer prospective but also from a client prospective who's gone through and seen changes since yo guys started with chatkit.

the packages are also far from reach for normal communities like forums. we are in a era where you can get server packages for $5 per month, you cannot possibly offer starting packages at $99 per month anyway!

 I don't really know what to say at this point. Quite frustrated  and upset about this.

the official launch blog post about "BBChat":
http://sitesplat.com/phpBB3/viewtopic.php?f=17&t=4761  

Dave

**Comment by CrazyC0d3r** [comment]
Pusher doesn't seem to have any direction going by all the random tier changes as of late. Pusher has proven to be untrustworthy so I have deleted all my pusher apps and my pusher account and won't use their services again.

**Comment by parthawasthi** [comment]
Hi Dave,

Thank you for being a Pusher user and for sharing your feedback with us — It is deeply appreciated. You've built an impressive product on our free "Sandbox" and can hopefully see the value Pusher Chatkit brings to it. We acknowledge that our most recent pricing change may not have aligned well with your expectations, but do allow us to explain:

1. We understand that our customers may be in different stages of rolling out their in-app chat experience with Chatkit. This is why, existing Chatkit customers have been grandfathered into the price plans they are on for the next 6 months. The new pricing changes will not affect you before then.
2. In June 2018, our product was in Beta; the pricing at that time was purely indicative and was subject to change. Since then, we have updated our prices to reflect the feedback we have received from our customers.
3. We believe our free plan is still fairly generous, but for small-scale (but production-grade) applications, our new $99 plan offers you the capabilities you expect from our platform and represents great value.

We have been trying to reach you through our Sales team to continue this conversation meaningfully. We are closing this GitHub issue, since it is not a product issue.

Thank you for your continued patronage and we are eager to work with you on this.

**Comment by cavive** [comment]
I also don't trust this.

**Comment by raykai** [comment]
I ask that you respect your words and regarding the free usage since March 2019 and bring back that tier:
https://gyazo.com/c5adafa012a7baf07374b8226ed51cef

**Comment by homekititalia** [comment]
Dear @SiteSplat (Davide Marafioti or you prefer your false name Dave Mara), they are serious... Only man is not serious is you!

**Comment by SiteSplat** [comment]
Well this just shows how serious Pusher is.
Disgraceful is the only word I can think right now.

https://sitesplat.com/phpBB3/viewtopic.php?f=17&t=5237
