### ISSUE TITLE
CurrentUser.cursors

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#34]
Good day to all! CurrentUser.cursors gives empty reply. How to use it? I thought it need to load last room where user was active.

**Comment by hot-leaf-juice** [comment]
Hi @alexey13! The `cursors` object isn't populated immediately, but it's guaranteed to be populated before any of your room subscriptions succeed, so you can safely use the cursors when processing a new message to see if you have seen it before or not.

In an upcoming release of the SDK the cursors _will_ be populated immediately, to avoid this confusion.

**Comment by alexey13** [comment]
Guys i cant understand how to work with cursors. I set cursor succesfully, but when i use currentUser.cursors i get empty object.

**Comment by hot-leaf-juice** [comment]
Hi @alexey13 the cursors object is not set immediately when you connect (because the state is retrieved as part of another request), but should be set by the time any subscriptions succeed, e.g.

    currentUser.subscribeToRoom(room, {
        newMessage: m => {
            if (m.id > currentUser.cursors[room.id]) {
                console.log('previously unseen message!', m)
            }
        }
    )

I hope this helps. We'll be releasing a new version of the library very soon which should make the cursors interface much simpler.

**Comment by hamchapman** [comment]
As @hot-leaf-juice said this will be fixed in the soon-to-be-released new version of the SDK.
