### ISSUE TITLE
Lets talk about online and offline presence updates

### ISSUE THREAD

**Issue by alexey13** [pusher/chatkit-client-js#35]
Hi to all!

Scenario 1
User1 connected at 13pm
User2 connected 5 minutes later

User1 will get status of user2.
But User2 wont get status of User1 until User1 refresh page.
But in that case they changed places, one of them not see online status

Scenario 2
User1 travel from page to page. User2 will see every time offline, online, offline, online......
Need to set timeout to 5 seconds of offline status by default i think.

About scenario 1 any thoughts?

**Comment by alexey13** [comment]
It would be great to have a list of connected users. When user connect to chatkit he get list of all online users.

**Comment by hot-leaf-juice** [comment]
The presence state of all users can be found buried deep inside the `CurrentUser` object, but getting hold of it isn't ideal, and it isn't populated immediately. This is something that should be fixed in an upcoming release of the SDK too. Would an interface something like the following make sense?

```javascript
const onlineUsers = currentUser.users.filter(user => user.presence.state === 'online')
```

Regarding scenario 2: we're planning a bit of an overhaul of how presence works at some point in the future, so this is certainly something we will consider then.

**Comment by alexey13** [comment]
I think when user connect to chat he get status online in list of all users and that status goes to all online users. When he disconnect status changed to offline and others get that update of status.

**Comment by hot-leaf-juice** [comment]
@alexey13 That's the idea yeah, it's just quite hard to extract the initial status at the moment. We're working on making that easier, by having the presence data always be available directly on the user object.

This functionality should be available in the next version.

**Comment by hamchapman** [comment]
As @hot-leaf-juice said this will be fixed in the soon-to-be-released new version of the SDK.
