### ISSUE TITLE
Subscribing to already subscribed channel

### ISSUE THREAD

**Issue by gaurav112** [pusher/chatkit-client-js#43]
I am using this js client in a cordova application. I am suscribing to all the rooms when connected(onSuccess). But wen the application looses connection and reconnects, the connection success is called again and messages are recieved the nuber of times the connection was made. I don't know if this is a bug or we as a developer have to handle this issue.

**Comment by hamchapman** [comment]
That does sound like a bug, and likely because subscriptions aren't being cleaned up appropriately. I _think_ this might be fixed in an upcoming release, the PR for which is here: https://github.com/pusher/chatkit-client-js/pull/31

That PR comes with a host of other changes though, in particular, moving to using Promises where possible in place of callbacks.

**Comment by hamchapman** [comment]
This should indeed be fixed in the upcoming release, the PR for which I linked to before. I'll close this issue for now as it will soon be resolved 👍 

Thanks!

**Comment by kristiankyvik** [comment]
I am experiencing the same problem here, has this been fixed already?

**Comment by hamchapman** [comment]
It should have been fixed when the linked PR (#31) was merged.

If you're experiencing a similar issue please could you create a new issue describing the problem and how to recreate it? Thanks!
