### ISSUE TITLE
Unread messages count of all my rooms

### ISSUE THREAD

**Issue by eveevans** [pusher/chatkit-client-js#67]
Is there a way to receive a count of all the unread messages or at least the amount of rooms with unread messages from all the current  User 's rooms ?

I know that you can access to the last cursor of each room. But some times this is very inefficient. 

Example: Imagine Facebook Message icon showing the amount of new messages, but it requests all the rooms (and their last messages) only when you click and open the menu)

**Comment by hamchapman** [comment]
Hey @eveevans - currently the method you described is the best way of getting the count of unread messages; using the cursor for each room.

However, we know it's not the easiest way of getting to the information you really want, namely the unread message count for each room. As such it's something that we're looking into making easier in the future, but we've not got a timeline just yet for when those changes will be implemented.

**Comment by eveevans** [comment]
Thanks @hamchapman 
The main problem with this method is that you have to subscribe to all the rooms in order to have an accurate unread  message count. But, for example if the user had 30 rooms, it will be very inefficient to subscribe to all rooms, read it last cursor and calculate the unread messages ... (lot of promises and frames jumping around)  :/

**Comment by gianpaj** [comment]
+1 on having one hook or a non-subscription-based function to get the number of unread messages

**Comment by abeltje1** [comment]
+1 for sure!

**Comment by senky** [comment]
+1

**Comment by kkcodes** [comment]
+1

**Comment by neuropass** [comment]
This is another must have for chatkit. Gaving an option for unread messages count could be implemented for scrolling to X messages etc. Very useful and adds a nice UX overall.

**Comment by hamchapman** [comment]
Hi @williamluke4, not yet I'm afraid. We're certainly aware of the desire for the feature and we'd like to support it in the future. It's just a question of prioritisation right now. We've got some other new features coming out very soon which have been our focus for a while so once all of that is sorted we'll be able to have a better idea of when something like this feature can be worked on 👍

**Comment by eveevans** [comment]
I'm feeling disappointed with the service.
The price its too high for having an incomplete API that lack of core utilities... and without a concrete date for releasing it u.u

**Comment by hcliff** [comment]
hey @hamchapman any movement on this? without this feature it's essentially impossible to build a chat app - a defining feature of chat apps (messages, whatsapp etc...) is that rooms with new messages are at the top of the list. Any roadmapping you can share would be really helpful for planning. thanks!

**Comment by williamluke4** [comment]
@hamchapman I really want to use your awesome service but there doesn't seem have been much movement or communication. Could we please get an update?

**Comment by wirecamp** [comment]
Same here. We really want to buy this but a lot of basic features are missing. We are currently doing a lot of hack, getting the last read of all the user subscribed rooms and comparing it with the latest message in the room to check if any unread message. This is an overkill.

**Comment by wirecamp** [comment]
I cannot believe these guys need more than 1 year to fix this issue . Bye chatkit. Off to sendbird

**Comment by parthawasthi** [comment]
Hi all.

We appreciate that this has been a long-awaited feature for many of you — we're sorry it has taken us a while to be able to accommodate this on the roadmap. Good news is: We're working on adding unread message counts as a property of the room entity, and aim to have it shipped by April 29th, 2019. 

FWIW, the reason this feature request has been such a long time coming is that, although inconvenient, it has been possible to calculate unread message counts. Other major features like OOB support for Push notifications, webhooks and multi-part messaging were prioritised because they were much harder (or impossible) to implement with the existing API.

Over the course of 2018, Pusher has gone through radical transformation organisationally and we are better equipped to both turn around new feature requests sooner, as well as to keep customers updated better through the process of doing so. This, however, means we cannot continue to accept feature requests through GitHub issues. For all future feature requests, we encourage you to email support@pusher.com. We will be closing this issue, and other such issues which are feature requests.

We thank you for your patience and continued support.

Parth

**Comment by MarkMurphy** [comment]
@parthawasthi Does closed mean shipped? or are we still waiting until the 29th of April?

**Comment by gianpaj** [comment]
@parthawasthi if Github is not the best place to request features and get alerted when they're shipped, what system/site will there be? public Trello board, Canny.io?

I believe a public website improves the communication and transparency with customers than a private email address

**Comment by jpbonjour** [comment]
Are you still on track to deliver an api update on 4/26? Else we need to leave Pusher in favor of Getstream

**Comment by callum-oakley** [comment]
@jpbonjour yes :)

**Comment by nathandaly** [comment]
👍  I am having that issue as I can only get a message count on the active room using onMessage subscription and mapping it but not all rooms at once.
